# Generated by Django 5.1.4 on 2025-01-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('task_type', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('super important', 'Super Important')], max_length=50)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50)),
            ],
        ),
    ]
