# Generated by Django 5.1.4 on 2025-01-16 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_task_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cat_name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='task',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
